BindSolution/Controllers/ProjectController.cs
// //-----------------------------------------------------------------------
// // <copyright file="ProjectController.cs" company="Bind Solution">
// //     Copyright (c) Bind Solution. All rights reserved.
// // </copyright>
// // <author></author>
// //-----------------------------------------------------------------------



namespace BindSolution.Controllers
{
    #region usings

    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using AutoMapper;
    using Binders;
    using Data;
    using Data.Extensions;
    using Data.Infra;
    using Extensions;
    using Filters;
    using Framework;
    using Framework.Web;
    using Framework.Web.Extensions;
    using Infra;
    using Microsoft.Security.Application;
    using Service;
    using ViewModel;

    #endregion

    public class ProjectController : BindController
    {
        #region Properties

        public IProjectService ProjectService { get; private set; }
        private readonly IProjectImageWrap _projectImageWrap;
        private readonly IAddressRepository _addressRepository;
        private readonly IProjectImageRepository _projectImageRepository;

        #endregion

        #region Constructor

        public ProjectController(IProjectService projectService, IProjectImageWrap projectImageWrap, IAddressRepository addressRepository, IProjectImageRepository projectImageRepository)
        {
            ProjectService = projectService;
            _projectImageWrap = projectImageWrap;
            _addressRepository = addressRepository;
            _projectImageRepository = projectImageRepository;
        }

        #endregion

        public ActionResult Index()
        {
            var list = ProjectService.Repository.Query().ToList();
            return View(list);
        }

        [ProjectHeader]
        public ActionResult About(Project project)
        {
            return View(project);
        }

        [ProjectHeader]
        public ActionResult Photos(Project project)
        {
            ViewBag.PathImageTumbsFormat = Path.Combine(string.Format(Constants.ProjectImageTumbsPathFormat, project.ID), "{0}");
            var pathFullImage = string.Format(Constants.ProjectImagePathFormat, project.ID);
            ViewBag.PathImageFormat = pathFullImage.Remove(pathFullImage.LastIndexOf('/'), 1);
            var images = project.Images.Select(p => new WebImage(Server.MapPath(Path.Combine(string.Format(Constants.ProjectImageTumbsPathFormat, project.ID), p.Name))));
            ViewData.Add("Images", images.ToList());
            return View(project);

        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Photos(Guid id)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in Request.GetFiles())
                {
                    Dictionary<string, Stream> filesSaved;
                    _projectImageWrap.Save(file.Key, file.Value, id, out filesSaved);
                    var project = ProjectService.Repository.Get(id);
                    foreach (var fileSave in filesSaved)
                        ProjectService.AddImage(fileSave.Key, project);
                }

                if (ProjectService.Repository.Save() > 0)
                    return AjaxRedirect("Photos");
            }
            return View();
        }

        [ProjectHeader]
        public ActionResult Addresses(Project project)
        {
            return Request.IsAjaxRequest()
                       ? (ActionResult)Json(project.Addresses.ToList(), JsonRequestBehavior.AllowGet)
                       : View(project);
        }

        [ProjectHeader]
        public ActionResult Admin(Project project)
        {
            var pathFullImage = string.Format(Constants.ProjectImagePathFormat, project.ID);
            ViewBag.PathImageFormat = pathFullImage.Remove(pathFullImage.LastIndexOf('/'), 1);
            return View(project);
        }

        #region Project

        [Authorize(Roles = RoleConstants.Administrators)]
        public ActionResult Create()
        {
            return View(new ProjectViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(ProjectViewModel model, bool redirect = true)
        {
            if (ModelState.IsValid)
            {
                model.Details = Sanitizer.GetSafeHtmlFragment(model.Details);
                model.SaveLogo(_projectImageWrap);

                var project = Mapper.Map<Project>(model);
                ProjectService.Repository.Add(project);



                if (ProjectService.Repository.Save() > 0)
                {
                    if (!redirect && Request.IsAjaxRequest())
                    {
                        var relativeLogoPath = string.Format(Path.Combine(Constants.ProjectImageTumbsPathFormat, "{1}"), project.ID, project.Logo);
                        var webImage = new WebImage(Server.MapPath(relativeLogoPath));
                        return Json(new
                                        {
                                            project,
                                            success = true,
                                            img = new { relativeLogoPath = Url.Content(relativeLogoPath), webImage.Width, webImage.Height },
                                            url = Url.Action("About", new { url = project.Keyword }),
                                            message = "Projeto cadastrado com suscesso!"
                                        });
                    }
                    return AjaxRedirect("Index");
                }
            }

            return AjaxResult(model);
        }


        [Authorize]
        [ProjectHeader]
        public ActionResult Edit(Project project)
        {
            ViewBag.Project = project;
            return View(Mapper.Map<ProjectViewModel>(project));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)] //TODO: REFACTOR: Desabilita toda a validação de HTML (Não recomendado!!)
        [Authorize]
        [ProjectHeader]
        public ActionResult Edit(ProjectViewModel model, Project project)
        {
            if (ModelState.IsValid && TryUpdateModel(project))
            {
                if (model.Logo != null)
                    _projectImageWrap.ReplaceLogo(project, ProjectService, model.Logo);

                project.Details = Sanitizer.GetSafeHtmlFragment(project.Details);
                if (ProjectService.Repository.Save() > 0)
                    return AjaxRedirect("About");
            }

            ViewBag.Project = project;
            return AjaxResult(model);
        }

        [ProjectHeader]
        [Authorize]
        public ActionResult Delete(Project project)
        {
            return View(project);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ProjectHeader]
        [Authorize]
        public ActionResult Delete(Project project, Guid id)
        {
            if (ModelState.IsValid)
            {
                ProjectService.Repository.Remove(project);
                if (_projectImageWrap.Delete(id) && ProjectService.Repository.Save() > 0)
                    return AjaxRedirect("Index");
                ModelState.AddModelError("", "Não foi possível remover o projeto");
            }

            return AjaxResult(project);
        }


        [Authorize]
        [ProjectHeader]
        public ActionResult Publish(Project project)
        {
            return View(project);
        }

        [HttpPost]
        [ProjectHeader]
        [Authorize]
        public ActionResult Publish(Project project, Guid? id, bool redirect = true)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    project.Published = !project.Published;

                    if (ProjectService.Repository.Save() > 0)
                    {
                        return !redirect && Request.IsAjaxRequest()
                                   ? Json(
                                       new
                                           {
                                               published = project.Published,
                                               keyword = project.Keyword,
                                               success = true,
                                               message = "Projeto " + (project.Published ? "publicado" : "despublicado") +
                                           " com suscesso!"
                                           })
                                   : AjaxRedirect("Admin");
                    }
                }
                ModelState.AddModelError("", "Não foi possível publicar o projeto");
                return AjaxResult(project);
            }
            catch (Exception ex)
            {
                return Json(new { keyword = project.Keyword, success = false, message = ex.GetInnerException().Message });
            }
        }

        #endregion

        #region Project Address

        [Authorize]
        [ProjectHeader]
        public ActionResult CreateAddress(Project project)
        {
            ViewBag.Project = project;
            return View(new AddressViewModel());
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)] //TODO: REFACTOR: Desabilita toda a validação de HTML (Não recomendado!!)
        [ProjectHeader(LoadAddresses = true)]

BindSolution/Views/Shared/_BlogRss.cshtml
@using System.ServiceModel.Syndication
@using Microsoft.Web.Samples
@model IEnumerable<SyndicationItem>


@if (Model != null && Model.Count() > 0)
{
        foreach (var blogEntry in Model)
        {
            <li>
                <div class="blog-date">
                    @Sprite.Image("~/App_Sprites/home/calendar.png", new { alt="Calendário" })
                    <span class="blog-dateDay">@blogEntry.PublishDate.Day</span>
                    <span class="blog-dateMonth">@blogEntry.PublishDate.ToString("MMMM").Substring(0, 3)</span>
                </div>
                <div class="blog-text">
                    <a href="@blogEntry.Links[0].Uri" target="_blank" title="@blogEntry.Title.Text">
                        <h4>@blogEntry.Title.Text</h4>
                    </a>
                    <p>@Html.Raw(blogEntry.Summary.Text)</p>
                </div>
            </li>
        }
    
}
else
{
    <li>
        <p class="sub-title space-container">Nenhuma entrada no blog</p>
    </li>
}

BindSolution/Views/Shared/_Projects.cshtml
@using BindSolution.Data
@using BindSolution.Infra
@using Microsoft.Web.Samples
@model IEnumerable<Project>

@if (Model != null && Model.Count() > 0)
{
    <ul class="projects">
        @foreach (var project in Model)
        {
            var pathFormat = Path.Combine(Constants.ProjectImageTumbsPathFormat, "{1}");
            var realtivePathImage = string.Format(pathFormat, project.ID, project.Logo);
            var webImage = new WebImage(Server.MapPath(realtivePathImage));

            <li>
                <div class="item">
                    <a href="@Url.Action("About", "Project", new { url = project.Keyword })" class="frame" title="@project.Description">
                        <div>
                            <img src="@Url.Content(realtivePathImage)" alt="@project.Name" width="@webImage.Width" height="@webImage.Height" />
                        </div>
                        <span class="title">@project.Name</span>
                    </a>
                </div>
            </li>
        }
    </ul>
}
else
{
    <div class="no-data">
        @Sprite.Image("~/App_Sprites/home/empty.png")
		<p>nenhum projeto cadastrado!</p>
	</div>    
}

BindSolution/Views/Shared/_TopMenu.cshtml
@using BindSolution.Data.Infra
@using BindSolution.Framework.Web.Extensions;
<ul id="top-menu">
            
    @*     
    <li>
        <p>Generate at: @DateTime.Now</p>
    </li>
    *@

    @if (Request.IsAuthenticated)
    {
        <li id="username-menu">
            <p>@User.GetUser().Name | @User.Identity.Name</p>
            @if (User.IsInRole(RoleConstants.Administrators))
            {
                <a href="/elmah.axd" target="_blank" class="link" title="Log de erros">Elmah</a>
            }
            @Html.ActionLink("Sair", "LogOut", "Account", null, new { @class = "link" })
        </li>
    }
    else
    {
        <li>
            @Html.ActionLink("Login", "LogOn", "Account", new { returnUrl = HttpContext.Current.Request.RawUrl }, null)
        </li>
    }


</ul>

BindSolution/Views/Shared/_Twitter.cshtml
@model List<TwitterDataViewModel>


@if (Model != null && Model.Count() > 0)
{
    foreach (var twitter in Model)
    {
        <li>
            <div class="content">
                @Html.Raw(twitter.Content)
            </div>
            <p class="time message">@twitter.Updated</p>
        </li>
    }
}
else
{
    <p class="sub-title">Nenhum twitter</p>
}